//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent_Roster
    {
        public long Event_Roster_Id { get; set; }
        public Nullable<long> Event_Id { get; set; }
        public Nullable<long> Contact_Id { get; set; }
        public Nullable<decimal> Contact_Hours { get; set; }
        public Nullable<System.DateTime> Create_Datetime { get; set; }
        public Nullable<System.DateTime> Modified_Datetime { get; set; }
    
        public virtual tblContact_Person tblContact_Person { get; set; }
        public virtual tblEvent_Info tblEvent_Info { get; set; }
    }
}
