//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tblPgmRelationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LU_tblPgmRelationType()
        {
            this.tblContact_PgmRelation_Types = new HashSet<tblContact_PgmRelation_Types>();
        }
    
        public int PgmRelation_Type_Id { get; set; }
        public string PgmRelation_Type_Desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContact_PgmRelation_Types> tblContact_PgmRelation_Types { get; set; }
    }
}
