//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tblPgmRelationType
    {
        public int Type_Id { get; set; }
        public string Type_Desc { get; set; }
    
        public virtual tblContact_PgmRelation_Types tblContact_PgmRelation_Types { get; set; }
    }
}
