//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonation_Info
    {
        public long Donation_Id { get; set; }
        public string Donor_First_Name { get; set; }
        public string Donor_Last_Name { get; set; }
        public string Donor_Contact_Type { get; set; }
        public string Is_Donor_Org_Ind { get; set; }
        public string Is_Org_Gift { get; set; }
        public string Donor_Type { get; set; }
        public string Donor_Email_Id { get; set; }
        public string Donor_Employer { get; set; }
        public string Campaign_Name { get; set; }
        public Nullable<decimal> Transaction_Amt { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Transaction_Type { get; set; }
        public string Transaction_ID { get; set; }
        public Nullable<System.DateTime> Load_Datetime { get; set; }
        public Nullable<System.DateTime> Modified_Datetime { get; set; }
        public Nullable<long> Donor_Contact_Id { get; set; }
    }
}
