//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent_Info()
        {
            this.tblEvent_Roster = new HashSet<tblEvent_Roster>();
        }
    
        public long Event_Id { get; set; }
        public Nullable<int> Event_Type_Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
        public Nullable<System.DateTime> Planned_Start { get; set; }
        public Nullable<System.DateTime> Planned_End { get; set; }
        public Nullable<decimal> Event_Duration { get; set; }
        public string Location_Name { get; set; }
        public string GPS_Location { get; set; }
        public Nullable<long> Primary_Contact { get; set; }
        public string Addr_Street { get; set; }
        public string Addr_City { get; set; }
        public string Addr_State { get; set; }
        public string Addr_ZipCode { get; set; }
        public Nullable<System.DateTime> Create_Datetime { get; set; }
        public Nullable<System.DateTime> Modified_Datetime { get; set; }
        public string Active_Ind { get; set; }
        public Nullable<long> Adult_Cnt { get; set; }
        public Nullable<long> Child_Cnt { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public Nullable<decimal> Average_Score { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public string Notes { get; set; }
        public string Photo_Release_Ind { get; set; }
        public string Photo_Code { get; set; }
        public Nullable<int> Involved_Org_Cnt { get; set; }
    
        public virtual LU_tblEventStatus LU_tblEventStatus { get; set; }
        public virtual LU_tblEventStatus LU_tblEventStatus1 { get; set; }
        public virtual LU_tblEventType LU_tblEventType { get; set; }
        public virtual LU_tblEventType LU_tblEventType1 { get; set; }
        public virtual tblContact_Person tblContact_Person { get; set; }
        public virtual tblContact_Person tblContact_Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvent_Roster> tblEvent_Roster { get; set; }
    }
}
