//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UGLEntities : DbContext
    {
        public UGLEntities()
            : base("name=UGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LU_tblContactType> LU_tblContactType { get; set; }
        public virtual DbSet<LU_tblEvent_Role> LU_tblEvent_Role { get; set; }
        public virtual DbSet<LU_tblEventStatus> LU_tblEventStatus { get; set; }
        public virtual DbSet<LU_tblEventType> LU_tblEventType { get; set; }
        public virtual DbSet<LU_tblPgmRelationType> LU_tblPgmRelationType { get; set; }
        public virtual DbSet<tblContact_Org> tblContact_Org { get; set; }
        public virtual DbSet<tblContact_Person> tblContact_Person { get; set; }
        public virtual DbSet<tblContact_Person_Types> tblContact_Person_Types { get; set; }
        public virtual DbSet<tblContact_PgmRelation_Types> tblContact_PgmRelation_Types { get; set; }
        public virtual DbSet<tblDonation_Info> tblDonation_Info { get; set; }
        public virtual DbSet<tblEvent_Info> tblEvent_Info { get; set; }
        public virtual DbSet<tblEvent_Roster> tblEvent_Roster { get; set; }
        public virtual DbSet<vwEvent_Attendance> vwEvent_Attendance { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
