//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEvent_Attendance
    {
        public Nullable<short> Year_Id { get; set; }
        public Nullable<short> Month_Num { get; set; }
        public long Event_Roster_Id { get; set; }
        public Nullable<long> Event_Id { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
        public Nullable<decimal> Event_Duration { get; set; }
        public Nullable<long> Contact_Id { get; set; }
        public Nullable<decimal> Contact_Hours { get; set; }
        public Nullable<int> Contact_Event_Role { get; set; }
        public Nullable<int> Event_Type_Id { get; set; }
        public string Event_Type_Desc { get; set; }
        public string Event_Role_Desc { get; set; }
    }
}
